# Generated by Django 4.0.3 on 2022-04-04 17:06

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("first_name", "last_name", "username"),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="fb_image",
            field=filebrowser.fields.FileBrowseField(
                blank=True, max_length=200, null=True, verbose_name="Image"
            ),
        ),
    ]
