# Generated by Django 4.0.2 on 2022-02-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='immutable',
        ),
    ]
