# Generated by Django 4.0.3 on 2022-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_profile_fb_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="anonymize",
            field=models.BooleanField(
                default=False,
                help_text="Anonymize your account in public pages",
                verbose_name="Anonymize",
            ),
        ),
    ]
