# Generated by Django 4.0.2 on 2022-02-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_imagedata_thumbnail_alter_imagedata_title'),
        ('users', '0004_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatar', to='pages.imagedata', verbose_name='Avatar'),
        ),
    ]
