# Generated by Django 4.1.13 on 2026-04-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="fb_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="temp_image",
        ),
    ]
