# Generated by Django 4.0.2 on 2022-02-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_imagedata_date'),
        ('users', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatar', to='pages.imagedata', verbose_name='Avatar'),
        ),
    ]
