# Generated by Django 4.0.3 on 2022-03-15 10:55

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine'),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads/images/users/', verbose_name='Immagine'),
        ),
    ]
