# Generated by Django 4.0.3 on 2022-03-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_fb_image_profile_temp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
