# Generated by Django 4.0.3 on 2022-03-21 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name', 'username'), 'permissions': [('can_not_change_profile', 'Immutable Profile')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_it',
            field=models.TextField(blank=True, null=True, verbose_name='Short bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='temp_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='uploads/images/users/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='body',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
