[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/starter-fullstack"]

[project]
name = "starter-fullstack"
version = "0.1.0"
description = "Django app for digitalkOmiX.com"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "django>=6.0",
    "psycopg2-binary",
    "django-allauth",
    "django-crispy-forms",
    "crispy-bootstrap5",
    "django-htmx",
    "django-modeltranslation",
    "environs[django]",
    "coverage",
    "django-debug-toolbar",
    "factory_boy",
    "django-tinymce",
    "pillow",
    "easy-thumbnails",
    "django-filer",
    "requests>=2.32.5",
    "jwt>=1.4.0",
    "django-filebrowser>=4.0.3",
    "django-admin-action-forms>=2.2.1",
]
