# Generated by Django 4.0.2 on 2022-02-22 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Will be used in captions', max_length=100, null=True, verbose_name='Description')),
                ('original', models.ImageField(upload_to='uploads/images/original/', verbose_name='Original image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Images',
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
