# Generated by Django 4.0.2 on 2022-02-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_imagedata_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/thumbnail/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
