# Generated by Django 4.0.2 on 2022-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_imagedata_thumbnail_alter_imagedata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='original',
            field=models.ImageField(null=True, upload_to='uploads/images/original/', verbose_name='Original image'),
        ),
    ]
