# Generated by Django 4.0.3 on 2022-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_article_body_en_article_body_it_article_intro_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug_en",
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(editable=False, null=True),
        ),
    ]
