# Generated by Django 4.0.3 on 2022-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_article_body_en_article_body_it_article_intro_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="body_en",
            new_name="body_de",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="intro_en",
            new_name="intro_de",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="title_en",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="articlecarousel",
            old_name="description_en",
            new_name="description_de",
        ),
        migrations.RenameField(
            model_name="footerlink",
            old_name="title_en",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="body_en",
            new_name="body_de",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="intro_en",
            new_name="intro_de",
        ),
        migrations.RenameField(
            model_name="homepage",
            old_name="title_en",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="homepagecarousel",
            old_name="description_en",
            new_name="description_de",
        ),
        migrations.RenameField(
            model_name="logo",
            old_name="title_en",
            new_name="title_de",
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-external-link", "Link esterno"),
                    ("fa-facebook", "Facebook"),
                    ("fa-instagram", "Instagram"),
                    ("fa-twitter", "Twitter"),
                    ("fa-linkedin", "LinkedIn"),
                    ("fa-github", "GitHub"),
                ],
                default="fa-external-link",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
    ]
