# Generated by Django 4.0.2 on 2022-02-25 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_imagedata_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
