# Generated by Django 4.0.3 on 2022-07-08 17:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_article_slug_en_article_slug_it"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_it",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-external-link", "Link esterno"),
                    ("fa-facebook", "Facebook"),
                    ("fa-instagram", "Instagram"),
                    ("fa-twitter", "Twitter"),
                    ("fa-linkedin", "LinkedIn"),
                    ("fa-github", "GitHub"),
                ],
                default="fa-external-link",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
    ]
