# Generated by Django 4.0.3 on 2022-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_rename_body_en_article_body_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug_de",
            field=models.SlugField(
                help_text="Appears on the address bar", null=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(
                help_text="Appears on the address bar", null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                help_text="Appears on the address bar", null=True, verbose_name="Slug"
            ),
        ),
    ]
