# Generated by Django 4.0.3 on 2022-04-28 16:35

import django.utils.timezone
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_article_slug_en_article_slug_it"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shotgun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the article",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                ("body", models.TextField(null=True, verbose_name="Text")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shotgun article",
                "verbose_name_plural": "Shotgun articles",
                "ordering": ["-date"],
            },
        ),
    ]
