# Generated by Django 4.0.3 on 2022-08-07 14:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_article_slug_de_article_slug_it_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_de",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_it",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_de",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_de",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_it",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
    ]
