# Generated by Django 4.0.3 on 2022-07-09 10:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_article_body_alter_article_body_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_it",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
    ]
