# Generated by Django 4.0.3 on 2022-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('link', models.URLField(verbose_name='Link')),
                ('icon', models.CharField(choices=[('fa-external-link-square', 'External link'), ('fa-facebook-square', 'Facebook'), ('fa-instagram-square', 'Instagram'), ('fa-twitter-square', 'Twitter'), ('fa-linkedin-square', 'LinkedIn'), ('fa-github-square', 'GitHub')], default='fa-external-link-square', max_length=50, verbose_name='Notify by email')),
            ],
            options={
                'verbose_name': 'Footer link',
                'verbose_name_plural': 'Footer links',
            },
        ),
    ]
