# Generated by Django 4.0.3 on 2022-07-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_homepage_body_alter_homepage_body_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_en",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
    ]
