# Generated by Django 4.0.3 on 2022-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_shotgun_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotgun",
            name="title",
            field=models.CharField(
                help_text="The title of the article",
                max_length=100,
                verbose_name="Title",
            ),
        ),
    ]
