# Generated by Django 4.0.3 on 2022-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='popup',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/popup/', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='wide',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/wide/', verbose_name='Wide'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(choices=[('fa-external-link', 'External link'), ('fa-facebook', 'Facebook'), ('fa-instagram', 'Instagram'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'LinkedIn'), ('fa-github', 'GitHub')], default='fa-external-link', max_length=50, verbose_name='Icon'),
        ),
    ]
