# Generated by Django 4.0.3 on 2022-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_imagedata_popup_imagedata_wide_alter_footerlink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Appears on first image', max_length=50, null=True, verbose_name='Title')),
                ('intro', models.CharField(blank=True, help_text='Website in few words', max_length=100, null=True, verbose_name='Subtitle')),
                ('body', models.TextField(blank=True, help_text='Talk about this website', null=True, verbose_name='Testo')),
                ('carousel', models.ManyToManyField(to='pages.imagedata')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
        ),
    ]
