# Generated by Django 4.0.3 on 2022-05-04 16:44

import django.db.models.deletion
import filebrowser.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_shotgun_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShotgunImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Used in captions",
                        max_length=200,
                        verbose_name="Description",
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=200,
                        null=True,
                        upload_to="uploads/images/shotgun/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shotgun_image",
                        to="pages.shotgun",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shotgun image",
                "verbose_name_plural": "Shotgun images",
            },
        ),
    ]
