# Generated by Django 4.0.3 on 2022-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_shotgunimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shotgun",
            name="fb_image",
        ),
        migrations.RemoveField(
            model_name="shotgun",
            name="image",
        ),
    ]
