# Generated by Django 4.0.3 on 2022-03-15 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='original',
            field=models.ImageField(help_text='Landscape and at least 1600px wide if you want to use\n            them in carousels', null=True, upload_to='uploads/images/original/', verbose_name='Original image'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/thumbnail/', verbose_name='Anteprima'),
        ),
        migrations.CreateModel(
            name='HomePageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Immagine')),
                ('description', models.CharField(blank=True, help_text='Will be used in captions', max_length=100, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_carousel', to='pages.homepage', verbose_name='Home Page')),
            ],
            options={
                'verbose_name': 'Home page carousel',
                'verbose_name_plural': 'Home page carousels',
                'ordering': ['position'],
            },
        ),
    ]
