# Generated by Django 4.0.3 on 2022-05-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_remove_shotgun_fb_image_remove_shotgun_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotgunimage",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Used in captions",
                max_length=200,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
