# Generated by Django 4.0.3 on 2022-03-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homepage_options_alter_imagedata_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='carousel',
        ),
    ]
