# Generated by Django 4.0.3 on 2022-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_alter_shotgunimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotgunimage",
            name="position",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Position"),
        ),
    ]
