# Generated by Django 4.0.3 on 2022-08-13 15:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_shotgunimage_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shotgunimage",
            options={
                "ordering": ["position"],
                "verbose_name": "Shotgun image",
                "verbose_name_plural": "Shotgun images",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_it",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_en",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_it",
            field=models.SlugField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_en",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_it",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Talk about this website",
                null=True,
                verbose_name="Text",
            ),
        ),
    ]
