# Generated by Django 4.0.3 on 2022-08-13 16:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_shotgunimage_options_alter_article_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotgun",
            name="body",
            field=tinymce.models.HTMLField(null=True, verbose_name="Text"),
        ),
    ]
