# Generated by Django 4.0.3 on 2022-03-20 22:29

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_logo_image_delete_imagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=models.TextField(blank=True, help_text='Talk about this website', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_it',
            field=models.TextField(blank=True, help_text='Talk about this website', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_en',
            field=models.CharField(blank=True, help_text='Website in few words', max_length=100, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_it',
            field=models.CharField(blank=True, help_text='Website in few words', max_length=100, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(blank=True, help_text='Appears on first image', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_it',
            field=models.CharField(blank=True, help_text='Appears on first image', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='description_en',
            field=models.CharField(blank=True, help_text='Will be used in captions', max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepagecarousel',
            name='description_it',
            field=models.CharField(blank=True, help_text='Will be used in captions', max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='logo',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='logo',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='icon',
            field=models.CharField(choices=[('fa-external-link', 'Link esterno'), ('fa-facebook', 'Facebook'), ('fa-instagram', 'Instagram'), ('fa-twitter', 'Twitter'), ('fa-linkedin', 'LinkedIn'), ('fa-github', 'GitHub')], default='fa-external-link', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=models.TextField(blank=True, help_text='Talk about this website', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='homepagecarousel',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Image'),
        ),
    ]
