# Generated by Django 4.1.1 on 2024-03-14 14:02

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pages", "0014_alter_shotgun_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotgunimage",
            name="filer_image",
            field=filer.fields.image.FilerImageField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shotgun_image",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
