# Generated by Django 4.1.13 on 2026-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0016_remove_shotgunimage_fb_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlecarousel",
            name="home",
        ),
        migrations.RemoveField(
            model_name="homepagecarousel",
            name="home",
        ),
        migrations.AlterField(
            model_name="footerlink",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-external-link", "Link esterno"),
                    ("fa-facebook", "Facebook"),
                    ("fa-instagram", "Instagram"),
                    ("fa-twitter", "Twitter"),
                    ("fa-linkedin", "LinkedIn"),
                    ("fa-github", "GitHub"),
                ],
                default="fa-external-link",
                max_length=50,
                verbose_name="Icon",
            ),
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="ArticleCarousel",
        ),
        migrations.DeleteModel(
            name="HomePage",
        ),
        migrations.DeleteModel(
            name="HomePageCarousel",
        ),
    ]
