# Generated by Django 4.1.13 on 2026-04-02 18:15

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("pages", "0017_remove_articlecarousel_home_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logo_image",
                to=settings.FILER_IMAGE_MODEL,
            ),
        ),
    ]
