# Generated by Django 4.1.13 on 2026-04-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_logo_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logo",
            name="fb_image",
        ),
    ]
