# Generated by Django 4.1.13 on 2026-04-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_remove_logo_fb_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerlink",
            name="icon",
        ),
    ]
