# Generated by Django 6.0.3 on 2026-04-06 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_remove_footerlink_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotgun",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
