# Generated by Django 6.0.3 on 2026-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_alter_shotgun_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotgun",
            name="slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                max_length=120,
                null=True,
                verbose_name="Slug",
            ),
        ),
    ]
