# Generated by Django 6.0.3 on 2026-04-19 10:20

import tinymce.models
from django.db import migrations, models

import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0022_shotgun_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotgun",
            name="body",
            field=tinymce.models.HTMLField(
                default=pages.models.default_intro, verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="shotgun",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="shotgunimage",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Position"),
        ),
    ]
