# Generated by Django 6.0.3 on 2026-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0023_alter_shotgun_body_alter_shotgun_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footerlink",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="footerlink",
            name="title_it",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="title_it",
        ),
        migrations.AddField(
            model_name="shotgun",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
    ]
