# Generated by Django 6.0.3 on 2026-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_remove_footerlink_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotgun",
            name="toot",
            field=models.BooleanField(
                default=False, verbose_name="Publish to Mastodon"
            ),
        ),
    ]
