# Generated by Django 6.0.3 on 2026-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_shotgun_toot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the story",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, null=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of the story",
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
        ),
    ]
