# Generated by Django 6.0.3 on 2026-05-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_story"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["title"],
                "verbose_name": "Shotgun story",
                "verbose_name_plural": "Shotgun stories",
            },
        ),
        migrations.CreateModel(
            name="Shot2Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Position"
                    ),
                ),
                (
                    "shot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shotgun_story",
                        to="pages.shotgun",
                        verbose_name="Article",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_shotgun",
                        to="pages.story",
                        verbose_name="Story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shotgun story association",
                "verbose_name_plural": "Shotgun story associations",
                "ordering": ["position"],
            },
        ),
    ]
