# Generated by Django 6.0.3 on 2026-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0027_alter_story_options_shot2story"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="shots",
            field=models.ManyToManyField(
                through="pages.Shot2Story", to="pages.shotgun"
            ),
        ),
    ]
