# Generated by Django 6.0.3 on 2026-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0028_story_shots"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shot2story",
            constraint=models.UniqueConstraint(
                fields=("shot", "story"), name="unique_shot_story"
            ),
        ),
    ]
